# SPDX-FileCopyrightText: Estonian Information System Authority
# SPDX-License-Identifier: MIT

name: CMake (Ubuntu Linux)

on: [push, pull_request]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:${{matrix.container}}
    strategy:
      matrix:
        container: ['22.04', '24.04', '26.04']
    timeout-minutes: 120

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - name: Install dependencies
      run: apt update -qq && apt install --no-install-recommends -y g++ make cmake libgtest-dev libpcsclite-dev libssl-dev pkgconf

    - name: Install gcc 12
      if: matrix.container == '22.04'
      run: |
        apt install -y gcc-12 g++-12
        update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 60 --slave /usr/bin/g++ g++ /usr/bin/g++-12
        update-alternatives --set gcc /usr/bin/gcc-12

    - name: Configure CMake
      run: cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -S . -B build

    - name: Build
      run: cmake --build build --config $BUILD_TYPE -j $(nproc)

    - name: Test
      run: ctest -V -C $BUILD_TYPE --test-dir build
